services:
  supabase-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=production
      - PORT=7777
    restart: unless-stopped
    volumes:
      # 可选：挂载日志目录
      - ./logs:/app/logs 